blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_pk>/<slug:post_slug>/', views.post_detail, name='post_detail'),
    path('user/news/', views.news_list, name='news_list'),
    path('user/news/reading/<int:post_id>', views.add_reading, name='add_reading'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('logout/', views.logout_view, name='logout_view'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
#from django.utils.text import slugify
from uuslug import slugify  # slugify из библеотеки uuslug делает транслитерацию кирилици в латиницу


class Post(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200)
    users_readers = models.ManyToManyField('auth.User', related_name='posts_readers', blank=True)

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id, self.slug])

    # создаем slug из title, в случае если пост создан через интерфейс сайта (а не через админку)
    def save(self, *args, **kwargs):
        if not self.slug:
            #self.slug = slugify(self.title, allow_unicode=True)
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Contact(models.Model):
    # user_from: ForeignKey для пользователя, который создает связь
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    # user_to: ForeignKey для пользовтеля являющегося отслеживаемым
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)

# динамически добавляем поле к User
User.add_to_class('following', models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))

blog/forms.py
from django import forms
from .models import Post



class LoginForm(forms.Form):
    username = forms.CharField(label='Логин')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')
        widgets = {'title': forms.TextInput(attrs={'size': 60}), 'body': forms.Textarea(attrs={'rows':4, 'cols':70}),}
        labels = {'title': 'Название поста', 'body': 'Текст поста', }
 

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Contact
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, PostForm


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True).exclude(username=request.user)
    return render(request, 'blog/user/user_list.html', {'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'blog/user/user_detail.html', {'user': user})


# подписаться/отписаться на какого либо автора
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return redirect('blog:user_list')
        except User.DoesNotExist:
            return redirect('blog:user_list')
    return redirect('blog:user_list')


def post_list(request):
    posts = None
    if request.user.is_authenticated:
        if request.method == 'POST':
            form_post = PostForm(request.POST)
            if form_post.is_valid():
                cd = form_post.cleaned_data
                new_post = form_post.save(commit=False)
                new_post.author = request.user              
                new_post.save()
                return redirect('blog:post_list')
        else:
            form_post = PostForm()
        posts = Post.objects.filter(author=request.user)       
        return render(request, 'blog/post/list.html', {'posts': posts, 'form_post': form_post})
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user = authenticate(request, username=cd['username'], password=cd['password'])
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('blog:post_list')
                    else:
                        return HttpResponse('Disabled account')
                else:
                    return HttpResponse('Invalid login')
        else:
            form = LoginForm()
        return render(request, 'blog/post/list.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('blog:post_list')


@login_required
def post_detail(request, post_pk, post_slug):
    post = get_object_or_404(Post, id=post_pk, slug=post_slug)
    return render(request, 'blog/post/detail.html', {'post': post})


# лента новостей
@login_required
def news_list(request):
    user_list = []
    read = []
    followers = Contact.objects.filter(user_from=request.user)
    for u in followers:
        user_list.append(u.user_to)      
    followers_posts = Post.objects.filter(author__in=user_list)
    reads = User.objects.values('posts_readers').filter(id=request.user.id)   
    for r in reads:
        read.append(r['posts_readers'])
    return render(request, 'blog/post/news_list.html', {'followers_posts': followers_posts, 'read': read})


# отмечаем пост прочитанным
@login_required
def add_reading(request, post_id):
    if post_id:
        try:
            post = Post.objects.get(id=post_id)
            post.users_readers.add(request.user)
            return redirect('blog:news_list')
        except:
            pass
    return redirect('blog:news_list')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <h1>{% if request.user.is_authenticated %}<a href="/blog">Блог автора {{ request.user.username }}</a>
    {% else %}Войдите, чтобы начать читать блог.{% endif %}</h1>
  <div id="content">

    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
  {% if request.user.is_authenticated %}
    <h1><a href="{% url "blog:logout_view" %}">Выйти</a></h1>
    <p><a href="{% url "blog:user_list" %}">Вывести список авторов</a></p>
    <p><a href="{% url "blog:news_list" %}">Лена новостей</a></p>
  {% else %}
    <h1>Войдите</h1>
      <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Войти"></p>
      </form>
  {% endif %}
  </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Блог{% endblock %}

{% block content %}

<div>
    <div style="clear: both">
   {% if request.user.is_authenticated %}
    <h3>Создать новый комментарий</h3>
      <form action="." method="post">
        {{ form_post.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Отправить"></p>
      </form>
  {% endif %}
  </div>
  <div style="clear: both">
  <hr><hr><hr>
  {% for post in posts %}   
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      {{ post.author }} {{ post.created }} 
    </p>
      {{ post.body|truncatewords:30|linebreaks }}
    <hr>
  {% endfor %}
  </div>
</div>
{% endblock %}

blog/templates/blog/post/news_list.html
{% extends "blog/base.html" %}

{% block title %}Персональная лента новостей{% endblock %}

{% block content %}
  {% for post in followers_posts %}
    {% if post.author != request.user %} 
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      {{ post.author }} {{ post.created }} 
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
      <p  style="color:green">
      {% if post.id in read %}
        <i>Уже прочитано</i>{% else %}
        <a href="{% url "blog:add_reading" post.id %}">Отметить прочитанным</a>
      {% endif %}
      </p>
     <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

blog/templates/blog/user/user_detail.html
{% extends "blog/base.html" %}

{% block title %}{{ user.get_full_name }}{% endblock %}

{% block content %}
  <h1>{{ user.get_full_name }}</h1>
  {% with total_followers=user.followers.count %}
    <p>{{ total_followers }} подписчиков</p>
    <form action="{% url "blog:user_follow" %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ user.id }}"/>
        <input type="hidden" name="action" value="{% if request.user in user.followers.all %}unfollow{% endif %}follow"/>
      {% if request.user not in user.followers.all %}
        <input type="submit" value="Подписаться"/>
      {% else %}
        <input type="submit" value="Отписаться"/>
      {% endif %}
    </form>
  {% endwith %}
{% endblock %}

blog/templates/blog/user/user_list.html
{% extends "blog/base.html" %}

{% block title %}Блогеры{% endblock %}

{% block content %}
  <h3>Для того чтобы подписаться/отписаться выберите соответствующего автора:</h3>
    <hr>
  <div>
    {% for user in users %}
      <div>
        <a href="{{ user.username }}">{{ user.username }}</a> 
      </div>
    {% endfor %}
  </div>
{% endblock %}